// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootApp) DeepCopyInto(out *SpringBootApp) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootApp.
func (in *SpringBootApp) DeepCopy() *SpringBootApp {
	if in == nil {
		return nil
	}
	out := new(SpringBootApp)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpringBootApp) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootAppList) DeepCopyInto(out *SpringBootAppList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SpringBootApp, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootAppList.
func (in *SpringBootAppList) DeepCopy() *SpringBootAppList {
	if in == nil {
		return nil
	}
	out := new(SpringBootAppList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpringBootAppList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootAppSpec) DeepCopyInto(out *SpringBootAppSpec) {
	*out = *in
	if in.JavaToolOptions != nil {
		in, out := &in.JavaToolOptions, &out.JavaToolOptions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.EnvFrom.DeepCopyInto(&out.EnvFrom)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootAppSpec.
func (in *SpringBootAppSpec) DeepCopy() *SpringBootAppSpec {
	if in == nil {
		return nil
	}
	out := new(SpringBootAppSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpringBootAppStatus) DeepCopyInto(out *SpringBootAppStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpringBootAppStatus.
func (in *SpringBootAppStatus) DeepCopy() *SpringBootAppStatus {
	if in == nil {
		return nil
	}
	out := new(SpringBootAppStatus)
	in.DeepCopyInto(out)
	return out
}
